### ISSUE TITLE
Multiple tabs - Handle full tab stack

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#1144]
@davidzbiral Not sure if it's needed. Now tabs are limited to 20 and even on this number the label is very small.

Also need to think about the behavior when there is full count of tabs opened (20 now) and new entity is created. Open in tab and close the first one?

**Comment by davidzbiral** [comment]
@Ptrhnk : I think this is already not needed. Let's:
- avoid arrow down;
- limit the number of Detail tabs to 10 - nobody will need to have more, it would rather be that they forgot (or were lazy) to close those not needed any more;
- when the 11th tab is opened, the 1st one will close automatically. But how to determine the order? It would be great if it was the one with oldest activity (I mean: the oldest click on the tab), rather than the first in the chronological order of how they were initially opened. Is this reasonably simple to implement?

**Comment by Ptrhnk** [comment]
@davidzbiral It seems that the most efficient way to choosing the tab to close - by oldest activity - is sorting by order how tabs were opened (clicked) so It doesn't matter if something was changed inside.

If we try to use audit it would be possible to open tab without changes and then this one would be the first closed because of older audit.

**Comment by Ptrhnk** [comment]
Last conclusion: automatically close from the left with notification about closed tab

**Comment by davidzbiral** [comment]
I endorse this solution, thanks!
