### ISSUE TITLE
Move the technical documentation + manual to Github WIKI

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1196]
and keep the Readme file shorter (just an introduction)

**Comment by davidzbiral** [comment]
BTW @adammertel we are considering wiki also for our data collection guidelines (I tag @rljshaw) - and probably no need to make a specific wiki module on our server, rather let's use GitHub wiki for this.

**Comment by davidzbiral** [comment]
@adammertel : we are considering [BookStack](https://www.bookstackapp.com/) for DISSINET documentation, including for:
- Documentation of the Conceptual (i.e. non-technical) data model.
- Teaching materials on CASTEMO coding.
- Probably InkV user manual, since this is inseparable from teaching materials on the approach (and no reason to create separately).
- ... and BTW buch of our own private research documentation and knowledge base.

And with some public parts displayed at the InkVisitor website.

This being said, there is an argument to also document what I call the technical data model on the very same pages that will explain the conceptual data model, to have some extra layer of detail. Let's talk about it when we meet.

**Comment by davidzbiral** [comment]
Now it is ReliDocs.
