### ISSUE TITLE
Existing entity not found by Search and Suggester

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1521]
Entity labelled "[Secundum] dictum sororis Mayfrede de Pirovano" not found when searching "secundum dictum", and even "Mayfrede". Probably the parenthesis is the source of the problem? I guess parentheses (any kind) should be ignored in matching unless exact match is requested (to be implemented in a future search box)?

Same with Suggester - not found through Suggester either. 

Important - not finding an entity means that the user will create a spurious duplicate. Need it fixed by Mon 23 Jan.

**Comment by adammertel** [comment]
It works for me :/

![image](https://user-images.githubusercontent.com/12932677/213638446-7cd37a39-ca93-433a-9d84-6ba54d9afea9.png)
![image](https://user-images.githubusercontent.com/12932677/213638709-2da086ed-c9e8-423b-b515-9fe175070f59.png)

![image](https://user-images.githubusercontent.com/12932677/213638525-476a10d2-0bed-40d6-93e5-fb66313f6e1c.png)
![image](https://user-images.githubusercontent.com/12932677/213638625-352abaac-3310-4baa-9c05-e44d66667ce1.png)

**Comment by davidzbiral** [comment]
@adammertel : Works now for Mayfrede. But try "secundum Mayfrede" - doesn't work.
![obrazek](https://user-images.githubusercontent.com/55400794/213864845-e5ceef42-a45a-47b5-a8cf-834974e5786b.png)

**Comment by tomaham** [comment]
@davidzbiral The "secundum Manfrede" is a different thing than you originally reported.  

I don't know what the agreement about search is, but to make "secundum Manfrede" work, the search implementation would need to search also for tokenized expression (i.e. to understand input "secundum Manfrede" as ['secundum', 'Manfrede'] and ask for entities, where these two tokens are existing in any part of the label, i.e. not necessarily directly beside). 

I am only reacting to "without this, hck3 cannot happen" part of the issue,  because the search is fully functional (the brackets are not an issue), it just not implements this tokenized search, which is needed, it implements exact expression search.

**Comment by davidzbiral** [comment]
I spent a lot of time explaining what I want there some months ago and was still not successful. But I agree - the "hct3 cannot happen" is solved now, probably thanks to reparsing.

**Comment by jancimertel** [comment]
ad #1000 (main) or #1007 or #1009

I've just updated the filtration to allow such case: searching for label "Aword Bword Cword" using input "aword cword".
Order still needs to be respected - otherwise this could lead to another problems like how to check order of results.

https://user-images.githubusercontent.com/10438157/213946411-a1c1a73b-e37f-4c97-a375-7142bdc42ed7.mp4


If the order of input words must not be respected, i suggest we add different UI component to allow search by exact words(clone-able input with text "must include words").

**Comment by adammertel** [comment]
I am closing for now. The search will be refactored entirely in 1.3.3 anyway
