### ISSUE TITLE
On 13'' screens, the breadcrumb Subterritory navigation takes too much space

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1611]
On 13'' screens, the breadcrumb Subterritory navigation takes too much space. 
![obrazek](https://user-images.githubusercontent.com/55400794/219567713-bdfa7162-7f45-484e-ab28-4bae1973983e.png)

**Comment by Ptrhnk** [comment]
@davidzbiral This is too small for 13" I was thinking maybe it would help to zoom the fonts on tags, because there's not enough pixels to work with when you zoom that so much. Also if the resizing line is moving in opossite direction then the mouse, it means that you over exceeded our minimum size limits on boxes, basically it has to have some limits because sooner or later we run out of pixels. 

Adding video how does the resizing behaves when the width is smaller than minimum.
Just FYI: When I reproduce the look of interface I can measure 1100 px on width which is very low resolution for 13".

https://user-images.githubusercontent.com/29732281/219638069-f0e65673-31d3-4c14-9ae3-6d1ff5e4b4e3.mov

**Comment by Ptrhnk** [comment]
@davidzbiral The problem is basically not that everything doesn't fit when you zoom, there's basically not enough px to fit som many things.
The real question is why you need to zoom so much that we run out of pixels.
Is it because of the fonts on tags and tooltips?

**Comment by davidzbiral** [comment]
@Ptrhnk : The browser zoom in this screenshot is 100%!
In the following screenshot of the whole screen, just 90%, and even then the breadcrumb is too big and makes the statement list useless.
![Uploading obrazek.png…]()

**Comment by davidzbiral** [comment]
For my part, don't understand why the label of the Subterritory is so big.

**Comment by davidzbiral** [comment]
BTW as Adam knows, there are some editors even in DISSINET who avoid big screens and use InkV on 13'' screens. Not asking for mobile app :-) but with 13'' screens we must count.

**Comment by Ptrhnk** [comment]
> For my part, why not make the label of the Subterritory much smaller - no reason to have it so big.

@davidzbiral Yes I agree with shorter (narrower) label as I mentioned in the last comment.

I work on 13" too, and this is how it looks:
<img width="1440" alt="Screenshot 2023-02-18 at 6 29 40" src="https://user-images.githubusercontent.com/29732281/219845293-53891d1a-d864-48e3-b3ec-11bf67822a28.png">
What I'm trying to explain is, that it's not much relevant to talk about 13" as a size unit, because the space we can work with depends on the screen resolution (which you can find / change in settings) and not on the screen size.
In this picture I have 1440x900

I'll open new thread for discussing possibilities on this screen so it's not mixed.

**Comment by davidzbiral** [comment]
@Ptrhnk : OK, I'll try to remember that it is resolution which matters. This is mine on the 13'' display:
![obrazek](https://user-images.githubusercontent.com/55400794/220042143-b05a3ce6-1c65-4a80-b3a2-68903db09788.png)

**Comment by Ptrhnk** [comment]
@davidzbiral So here's the zoom.. This original resolution is even bigger than mine but the zoom is making it lower. It's 1920x1080 / 1.5 = 1280x720 -> so this is probably standard for 13" screen on windows and we can tweak our app for this resolution as the minimum.
