### ISSUE TITLE
In statement identification, do allow linking only the Entity class of the particular actant 

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1630]
Also, when the entity is unlinked from the actant position, and then a new entity is linked again to a different class of the identified entity, unlink the identified entity.

E.g., the user links person P1 to the statement and adds a  new in-statement identification with P2. Then he unlinks the P1 entity and links a group G1 to the actant slot. At this moment, having identification with P2 is illegal and should be prevented. 

@davidzbiral, what do you think? Should this be prevented for any costs or just highlighted as a warning for the user?

**Comment by davidzbiral** [comment]
@adammertel : I don't understand at all what is meant by "E class of the actant" and I do not understand this issue as a whole.

> E.g., the user links person P1 to the statement and adds a new in-statement identification with P2. Then he unlinks the P1 entity and links a group G1 to the actant slot. At this moment, having identification with P2 is illegal and should be prevented.

Why? Identification across the entity type boundary (e.g. a L and an O) should be allowed and is one important function of IDE (both in-statement and meta). E.g. if something happens on a boat, this boat is a ("floating") Location, if only because location relations should only take locations. But if somebody sells it, it is an Object. And this O and L will be identified.

**Comment by adammertel** [comment]
Great, thanks for the clarification :)

But is this rule (an entity can be "identified" with an entity of any class, e.g., P is identified as G) applicable also to non-statement Identifications? 
Because at this moment, we allow only same-class (non-Statement) identifications.

**Comment by davidzbiral** [comment]
Yes please, this applies meta-Identification as well. We should find a clearer notation for PLOGESTRB-PLOGESTRB, because from this it is not clear that it also means O-L. Of course, only some combinations are meaningful in the DISSINET's outlook at the world, but we will not lock those "unlikely" combinations in CASTEMO knowledge graphs.

**Comment by adammertel** [comment]
In this case it was noted as P-P O-O...
But okey, let's remove the condition for same entity classes in
identifications.

**Comment by davidzbiral** [comment]
Yes, let's do it.
