### ISSUE TITLE
possible bug in data collection if done through statement copy (i.e. via "duplicate" function): Actant slots and Action instance are not newly created (with new uuids) but copied (they have original uuid)

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#1786]
**The problem**

See neo4j visualisation of certain statement in DDB1
![image](https://github.com/DISSINET/InkVisitor/assets/3739529/257fa1ef-47f9-4f0e-b81d-80d3e5a099f5)

This is result of
`MATCH (s1:Statement)
WHERE (s1.uuid = "80354e69-71d4-4867-92d4-cd091201b1d8")
RETURN s1`

_Robert's report:_
If you open the statement, you will see that it has two subjects. One is correct (Petrus), the other is not (Stephanus) - Stephanus is not there in the coding. But, the statement I used to construct the one for Petrus was actually copied from Stephanus's territory I think (he is the previous person). I copied it in and changed the actants. And I definitely changed the actants correctly, double checked in InkV. But we still have Stephanus's "ghost" in the statement, at least in Neo4J. Interestingly, I cannot see Stephanus's UUID (ce3802f9-4281-4333-89c2-b03082fa7af4) in the JSON for the statement though - which seemed the most obvious culprit (although it is good that this is not it or we would have major, major issues to fix in our collected JSON data)So, somewhere in the import, a link to Stephanus as a subject is being recreated - any idea why? The other examples seem similar from what I can see, but I can add more if it helps (edited)

**The trace**
If you open the entities.json, you will find that actant with id "e7539053-0484-4720-b2df-d29617a62b87" is used within the statement with id "80354e69-71d4-4867-92d4-cd091201b1d8" (statement Robert is reporting) and within statement with id "5188881c-0b1f-4aff-92be-6087b404dd0c". I.e. it seems that there are two objects with the same actant id but with different content (entityId) are existing in the data as a result of the statement copy operation.

I guess that a copy of a statement is not creating **copies** of its inner entities. Even though it is just using the original objects, because it saves them within the statement, it does not overwrite originals.

**Comment by tomaham** [comment]
Implication for neo4j connection - if we would connect just the statement and person (without actant node with the same is as intermediary), we would actually get the data right.

Maybe this is not bug, but just unintended usage of the data model?

**Comment by rljshaw** [comment]
Great identification of the issue - I can see this in many other occasions where the statements have been copied and then changed in my Niort coding: the content of the actant slots have changed, but the uuid of the actant (i.e. actant slot) itself remains the same on all the statements copies.

I spot one other thing too which I think has the same origin: **sAction uuid (i.e. _the uuid of the instance of the Action_, not the Action type) also seems to not to havve changed when a statement has been copied**. 

See the neo4J projection below 
![sfuit](https://github.com/DISSINET/InkVisitor/assets/94554037/72332636-072d-49af-8c99-3d782ec35f37)

This leads to several issues - you can see here multiple statements are connected to the same sAction, which is obviously not right (multiple statements should not share the same Action instance, even if they share the same Action type). Elsewhere this is not occuring, just not in cases where a copy has been done from an original statement with this Action instance. It leads to a funny effect too of the sAction having two Action types - because, in one of the copied statements, the Action type was changed from "fuit" to "defendit", but the Action instance uuid of course remained the same.

So to me this looks like the same problem. We could see it as an unintended use of the data model - but the sAction issue I think places it more in the realm of bug. While with Actants slot entitiies, we could imagine skipping them in Neo4J projection; but we can't do so with sAction, Action instances like this are important to separate since they have properties applied to them directly.

It does seem, however, like a bug that (at least theoretically...) seems reasonably fixable as a batch operation in DDB1 (although I imagine all such operations are fraught!): simply put, **any Actant (slot, not content) and Action instance should have a unique uuid, they should not carry over multiple statements. If it does not, it should be given one.**

**Comment by rljshaw** [comment]
I think this **issue needs quite quick resolution,** since:
1) it could **potentially be creating quite a mess in DDB1 data as people continue to add data** making use of the "duplicate" facility in InkV
2) and also since it means that **some Neo4J projections both @davidzbiral and I were hoping to use for Leeds in 2 weeks time have inherited some issues** from this problem

**Comment by tomaham** [comment]
Any "copy operation" seems to produce an issue like this,  i.e., the prop objects are affected too.

I try to circumvent it by generating new UUIDs for actants, sAction and prop objects - all of these have relations to their master objects through "sitting in them", as far as I know, nothing is linking to UUIDs of these objects, they become relevant only in neo4j projections - that is why the inkvisitor ddb1 data are actually consistent.

Issue emerges only if we take uuids of actants, sActions and props seriously (which inkvisitor probably does not).

**Comment by davidzbiral** [comment]
To my mind: since actant uuid and sAction will be removed from the graph representation, it is not a huge issue, but it is clearly incorrect treatment of the data and should be solved promptly.

**Comment by rljshaw** [comment]
If we can find a workaround at the level of import, then that's fine. InkV itself ignores the issue, so if our import can follow the same path around it, then less of an issue.

Probably also worth fixing the duplicate function in InkV for the future though - in case further use creates unexpected issues that we struggle to solve this way

**Comment by adammertel** [comment]
Thanks for a this catch @tomaham, its a bug in Inkvisitor. We talked with @jancimertel, it should be fixed on the FE + a check on the BE. Also we want to go through all the data in the database and make sure all the identifiers are unique as the actants are never reused across the statements.
