### ISSUE TITLE
entity field "label"  and "labels"

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#2431]
As the alternative label was introduced, the entities now has new field labels which contain a list. 

If I look in the exported entity json,  some of the entities have both (label, labels) fields,  some just  one -  some surprisingly the multiple one
![image](https://github.com/user-attachments/assets/fbef18e1-e74e-4c22-8f02-0c96035a91d5)

This is intended behavior or bug?

**Comment by davidzbiral** [comment]
Sounds as a bit of a mess, explanation needed, @adammertel. There should always be a primary one, and secondary ones, in any case.

**Comment by adammertel** [comment]
@jancimertel created a database job that can be applied remotely. What deployment is it? We should ve able to fix it relatively quickly.

**Comment by davidzbiral** [comment]
@adammertel I don't understand the question. Tomáš's DDB2 production script into Neo4j ceased to work properly because of the introduction of alternative labels, that's what. And he seems to discover strange structures (uneven structure of entity fields if they have / don't have alternative labels) - please look into it as per his post.

This change should have been done in such a way that it does not really touch the old label, I guess...? Please study the problem.

We need to produce [this](https://docs.google.com/spreadsheets/d/1dEfD0-zUR0TjWplLHREB_xtNxtlU0fMOlqQnLAcl3Vg/edit?gid=2110914270#gid=2110914270) for a publication asap, and as you can see, many labels are missing (NaN / empty) in label and SCL_path now that alternative labels were introduced, and Tomáš also discovers some strange behaviour as he described it.

This is why you need to check whether the implementation of this data model change was an optimal one.

**Comment by tomaham** [comment]
This was the production inkVisitor.

**Comment by adammertel** [comment]
Thanks @tomaham, I think I understand now.

I checked the particular database but was not able to identify any invalid data (`labels` list is shorter than 1 or not existent)

![image](https://github.com/user-attachments/assets/75eb5085-a5c2-4954-bd98-973920085a0f)

Just to clarify what happened:
In the last version, a new feature was implemented - handling alternative labels (#2367). We have implemented this functionality by adding a new `labels` attribute to the entity model which is a list of strings. The first string is then used as the primary label, all the others (index 1+) are used as alternative / spelling variants. The original `label` attribute is therefore only a legacy thing that we did not try to remove completely for the cases like this one. But we are probably not keeping this consistent by not adding `label` attribute alongside `labels` when a entity is edited / created (would need to check this if you want to know). 

Sorry, this change could have been communicated better directly with you. If you could, please use the first `labels` element as the main label. If this is a problem from various reasons we can make sure to keep the original `label` in the database but it would be a duplication of information. 

If anything feel free to reach to me to discuss more details.

**Comment by tomaham** [comment]
I see. I was surprised by this parallel presence of legacy label in some and non-existing label in the new. I have expected either completely missing label, or legacy label everywhere.

>  But we are probably not keeping this consistent by not adding label attribute alongside labels when a entity is edited / created (would need to check this if you want to know).
This is the thing that you are most probably not doing - newly added entities did not have the label field if I recall rightly.

Np - I will change the code so I can read just the "labels" and take the name from the first position within the labels.
