### ISSUE TITLE
Statements panel: list of icons on hover prevents secure click on Edit

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#433]
Not good implementation yet - often I want to edit and instead the edit button is hidden by this list of icons.
![obrazek](https://user-images.githubusercontent.com/55400794/136465370-7db50da5-8381-4dd9-8d1c-184ab951f1f8.png)
Never allow this menu of actions on hover from hiding the edit button, which is by far the most important action. Also, sometimes the menu appears even if when I am moving to Edit and not to the icon of the menu - more testing needed.

**Comment by Ptrhnk** [comment]
OK, I will think about more robust solution for this component.
But for testing purposes - please try refreshing the page and then try it. We still need to implement automatic page resizing (I already added it to issues) because position of menu is now counted related to panel sizes.. so when there is not current page size set its possible that menu is not in the right place. I will solve both issues, but let me know If it works with refreshing, just for me to understand this behavior.
