### ISSUE TITLE
Consolidating information within Statement Editor / Statement Detail

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#510]
@davidzbiral 

The attributes of the statement are now dispersed between two components/boxes - `Statement Editor` and `Actant Detail`. 

 - A user may want to fill in all information directly in `Statement Editor` (without opening the actant in `Actant Detail`). Should we allow this? That means, do we want to move the inputs of label, detail, language, and status to `Statement Editor`?  

- The notes attributes seems like a duplication. Should we unify them?  

![image](https://user-images.githubusercontent.com/12932677/139595795-9958126a-6899-4229-ba0c-14fe81e0effc.png)

**Comment by davidzbiral** [comment]
For Statements, I do _not_ want to have label and detail and language in Editor, because it would prompt editors to fill them in, which for normal statements from sources is unnecessary (even spurious). Also, it is good for consistency of GUI that language etc. is edited always on the same spot, i.e. through Detail, whatever the entity type.
So let us leave these things in Detail only.

As for the **notes**: at the level of data model, this is of course the same thing indeed.
Solution in GUI: I understand the problem, and don't know. Is it acceptable that the duplication is there and that the text I write in the one or the other appears in both text fields upon writing? It is strange, I know, but can think of no better way for Statements. What you have in the screenshot is not a very typical situation - on the right, there will rarely be the same statement as in Detail, I think. Mind that Detail allows to edit entities which are not now in the Editor, and so we do not want to make Editor the way to edit notes. So the default place should be Detail, for this situation. I.e., better not to jump to Editor for editing notes - the user probably wants to have something different there at this moment.

**Comment by adammertel** [comment]
Thanks @davidzbiral, 
so consider the first part of the question as answered. 

For the second (notes), there are two solutions:
 - remove notes from Statement Editor
 - keep it as it is (keep the notes inputs in both Statement Editor and Detail) but consolidate the notes so they are the same attribute in the data model

**Comment by davidzbiral** [comment]
B is better - it absolutely should be the same attribute in the data model. Tx!
