### ISSUE TITLE
Entity reference source and value in data model

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#803]

**Comment by davidzbiral** [comment]
This is to relate entities to e.g. a gazetteer or a treebank.
-> Latin WordNet -> a0071
-> Geonames -> 2988506
It will _not_ be used to solve S-R relation (which remains as it was) or T-R relation (which will be done through metaprops).

It will be located before the "note", and one entity can have more of those relations.

**Comment by davidzbiral** [comment]
Put it in the data model of **all entities** (there are gazetteers for L, prosopographic databases for P...). I.e., not for A and C only but any entity type.

**Comment by adammertel** [comment]
Will we have some class-specific reference sources? E.g., reference sources just for Persons... ?

**Comment by davidzbiral** [comment]
@adammertel : Sure, e.g. Geonames is only for L, it is not a catalogue of P. Why are you asking?

**Comment by adammertel** [comment]
Ideally, could you please provide me a first list of the reference sources with their allowed entity classes?

**Comment by adammertel** [comment]
The Reference section in the detail box is created 
![image](https://user-images.githubusercontent.com/12932677/156934061-f303143c-447f-45a3-8bd6-02b397c2144c.png)

**Comment by davidzbiral** [comment]
@adammertel : good job, accepted.

**Comment by adammertel** [comment]
Thank you @davidzbiral, I will include this list in the dictionary. 
Detail about each source is a good idea, but I am not sure if mouseover popup is a good idea (you will probably like to show some URLs...). But we can try - could you provide these detail texts?

**Comment by davidzbiral** [comment]
@adammertel : Probably let us drop the idea of the detail, not so important. Anyway, deep in my heart I know that these things should be R entities rather than dictionary items, and then their detail would be solved by the general mouseover over any entity.

**Comment by adammertel** [comment]
@davidzbiral So definitely dropping this idea? The change is affecting the data model so it is a good idea to decide now. 
I would suggest keeping it as it is (the meta props will mess the layout a bit and they are mostly for something else than).
But its up to you

**Comment by tomaham** [comment]
If I may...
(I understand the context very loosely, so feel free to ignore me)

1) the problem has three dimensions:  GUI, data model,  modification of data model
2) dm: there is a notion of reference in statements which seem to go for R entity
3) dm and gui:  present solution creates two different kinds of "references" ?
4) mdm: where to define a possible allowed entity reference (present solution: in the code, later probably in some administration)

Are the 3, 4  the tensions in the mind?  They are in mine.

5) dm gui: from the GUI perspective it deserves a special place,  they even have a special field in the property of the entity, it makes sense  not to mess them together with all meta props, I agree with Adam totally

How about this:
6) entity references seem from the DM perspective the same problem as statement reference, i.e. why not make them as ref-relation-objects (with allowed type:R)  ?  And under entity references, the same GUI component for statement references can be used.

**Comment by tomaham** [comment]
Also the R resource entity could have a "part" label field, through which the user could control, what would be displayed in above the value of the entity-reference-relation dialogue, i.e. for text there would be "part", but for Resource Wordnet there could be "id". 

And in data model this would mean unification of IStatemeteReference and IEntityReference to one reference-relation object.

**Comment by davidzbiral** [comment]
@tomaham : Thanks for a voice in support of my concern - I feel the tension in No. 4 and very strongly the one in your No. 3. It simply does not feel right to rectify this only at the level of DDB2 which was, importantly, decided as a target _analysis_ format but no decision as yet that it is our _storage / interoperability_ format. In other words, even DDB1 data should be structured as neatly as possible, and neatly means that a very similar data structure should be stored a very similar way. I.e., in-statement ref. and this entity ref. should be structured in a similar way.

I.e., I am thinking the same way as you: having, alongside Prop object (or what's it called), which has the structure `origin-C-any entity type` a Reference object with the structure `origin-R-V`, the content of V denoting a closer identification: page for paginated resources, folio for leaf-numbered resources, ID for ID-based resources.

I am even ready to drop primary/secondary attribute of an in-statement ref., because this was more to keep a ref. to the manuscript alongside the edition, but perhaps the reference should be just to what we actually used for that statement - edition, manuscript, or both, but not marking primary/secondary. 

So I support the solution under No. 6! @adammertel , will you get persuaded if there is two of us? :-)

**Comment by adammertel** [comment]
The data model of DDB1 should stay as close as possible to the GUI. 
We should not compromise between two different goals of the data model.

But yes, making Entity Reference UI the same way as it is done in Statement editor is possible. 
So "Resource entity" -  "Part" tuples?

**Comment by tomaham** [comment]
@adammertel  But you are not for the data model unification of  StatementReference and EntityReference to one Reference object?

**Comment by davidzbiral** [comment]
Let's do it please... We're discussing with Robert whether we are ready to drop the distinction primary/secondary in StatementReference to unify the two models.

**Comment by adammertel** [comment]
That would be ideal.
Is this a formed task or just progress in the discussion at this moment? :) 
Ideally, create a new issue please with some detail and instruction.

**Comment by davidzbiral** [comment]
@tomaham @adammertel : I will make a new issue using and modifying your text, Tom - but still verifying the implications of dropping primary/secondary with Robert.

I think we will drop the super enhancement, because this kind of advanced validation is absent elsewhere - even in places where it is needed much more (e.g. our DISSINET-coder generated geo coordinates). We can come back to it as part of a broader validation dev.

On the other hand, I very much like the super ultra enhancement, doesn't seem complicated - the R model anyway already contains specifics, in this case, the url field, and adding a new field is not such a problem, is it.

@tomaham : what you are saying is that the R model has the field named "link" and you would (as I would too!) like to make it named "url"?

**Comment by davidzbiral** [comment]
Followed in #858, closing this.
