### ISSUE TITLE
S and E cannot be dragged and dropped

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#933]
Important bug: S and E cannot be dropped when dragging&dropping.
Tried from Statements to Editor: dropping to Actant and Prop value. The "no drop" mouse sign appears and the entity tag cannot be dropped.

![obrazek](https://user-images.githubusercontent.com/55400794/163722641-ba27cba7-1dc6-431a-88d6-446dc08532ee.png)

v. 1.2.0 | data-import | built: Thu 14.04.2022 17:38

**Comment by Ptrhnk** [comment]
https://user-images.githubusercontent.com/29732281/163795013-9fa6e734-87a5-4324-8fcd-ec283c134299.mov

**Comment by Ptrhnk** [comment]
@davidzbiral There's a problem with DnD (drag & drop) and notifications though. I'll try to explain it but it's complicated dev situtation. Javascript code is running mostly synchronously (not possible to do 2 operations at one time). So there is part of the code from DnD that is not running when notification is shown, because there is timeOut function in notification which is kind of "blocking" it. It would be propably possible to solve, but it's a bit problematic situation to handle. If you got more problems with it, we can make it priortity I guess. Not sure if to say it to others. Also restrict some notifications will help as a workaround (e.g. same as in editor we don't probably need notifications for new territory as it's shown after creation).

**Comment by Ptrhnk** [comment]
https://user-images.githubusercontent.com/29732281/164414519-51157cdb-3264-405d-a74a-464857a97195.mov

@davidzbiral tested in firefox and chrome on staging, can I close it or is it persisting?

**Comment by adammertel** [comment]
Just checked it and it is also working for me in all possible settings.

**Comment by davidzbiral** [comment]
Seems fixed, only the cursor/entity tag distance when browser window is zoomed in persists - described in another issue.
