### ISSUE TITLE
A button to open S entity (in the editor) from the Search box

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#955]
Double click opens the Entity in detail. Is there a need for a similar solution allowing the Statement to be opened in Editor?
A quick context menu on the right side? 
Right-click?
Or identifying "click-on-class" and "click-on-label" functions for Tag components?

**Comment by davidzbiral** [comment]
@adammertel : S can have _both_ things appended in Detail as metaprops (e.g. superclass), e.g. the superclass copied from a Statement template, _and_ things done in editor (perhaps superclasses of statements were not a good idea, but it was the best we were able to come up with to classify statements in the same trees as some composite concepts which denote a similar thing). So I think double-click does not work well - the expected behaviour is to open them in Detail, and it should not do a different thing.

The only possibility of different behaviour would be if Statements had no detail but everything was directly in the Editor window, e.g. the superclass. This we can consider - and then what you suggest would make sense.

**Comment by davidzbiral** [comment]
@adammertel I think that a statement can appear mostly in those situations:
- statement list; no problem opening;
- Detail (e.g. Used in); there the opening in the Editor already works;
- search results - there, please implement direct opening in Editor.
Elsewhere, not a priority, so the only thing which I think is a priority is quick open of Statements from Search results.

**Comment by adammertel** [comment]
Reformulated the issue

**Comment by davidzbiral** [comment]
@adammertel But what I am supposed to do?

**Comment by adammertel** [comment]
@davidzbiral I unassigned you here, as this would go to the implementation phase. You do not have to do anything here :)
