### ISSUE TITLE
Create entity from template / Use templates directly through Suggester 

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#957]
So when a user searches through suggester and a template fulfills the conditions (or a template Tag is dragged to the suggested), Inkvisitor creates a new Entity applying this template.

**Comment by davidzbiral** [comment]
Just be careful because our current workflow absolutely requires templates within templates - i.e. if in a template (entity template or statement template), the user should be able to choose the template _itself_ as the value of the entity tag, rather than only creating a new entity _based on_ the template. This only applies if in a template. (Since it makes no sense to include a template as actant of a non-template entity.)

**Comment by Ptrhnk** [comment]
ok so we agreed with @adammertel that if inside template than it's gonna be possible to choose if create new entity from template or assign template.
